sudo: required
services:
  - docker
before_install:
  - docker build -t tajpouria/wikipedia_graphql .
script:
  - docker run tajpouria/wikipedia_graphql yarn run test --scope=@tajpouria/examples
branches:
  except:
    - experimental