sudo: required
services:
  - docker
before_install:
  - docker build -t tajpouria/wikipedia_graphql .
script:
  - docker run tajpouria/wikipedia_graphql npm run test
branches:
  except:
    - experimental 